// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatadogDowntime extends pulumi.CustomResource {
    /**
     * Get an existing DatadogDowntime resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatadogDowntimeState, opts?: pulumi.CustomResourceOptions): DatadogDowntime {
        return new DatadogDowntime(name, <any>state, { ...opts, id: id });
    }

    public readonly active: pulumi.Output<boolean | undefined>;
    public readonly disabled: pulumi.Output<boolean | undefined>;
    public readonly end: pulumi.Output<number | undefined>;
    public readonly endDate: pulumi.Output<string | undefined>;
    public readonly message: pulumi.Output<string | undefined>;
    public readonly monitorId: pulumi.Output<number | undefined>;
    public readonly recurrence: pulumi.Output<{ period: number, type: string, untilDate?: number, untilOccurrences?: number, weekDays?: string[] } | undefined>;
    public readonly scopes: pulumi.Output<string[]>;
    public readonly start: pulumi.Output<number | undefined>;
    public readonly startDate: pulumi.Output<string | undefined>;

    /**
     * Create a DatadogDowntime resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatadogDowntimeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatadogDowntimeArgs | DatadogDowntimeState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: DatadogDowntimeState = argsOrState as DatadogDowntimeState | undefined;
            inputs["active"] = state ? state.active : undefined;
            inputs["disabled"] = state ? state.disabled : undefined;
            inputs["end"] = state ? state.end : undefined;
            inputs["endDate"] = state ? state.endDate : undefined;
            inputs["message"] = state ? state.message : undefined;
            inputs["monitorId"] = state ? state.monitorId : undefined;
            inputs["recurrence"] = state ? state.recurrence : undefined;
            inputs["scopes"] = state ? state.scopes : undefined;
            inputs["start"] = state ? state.start : undefined;
            inputs["startDate"] = state ? state.startDate : undefined;
        } else {
            const args = argsOrState as DatadogDowntimeArgs | undefined;
            if (!args || args.scopes === undefined) {
                throw new Error("Missing required property 'scopes'");
            }
            inputs["active"] = args ? args.active : undefined;
            inputs["disabled"] = args ? args.disabled : undefined;
            inputs["end"] = args ? args.end : undefined;
            inputs["endDate"] = args ? args.endDate : undefined;
            inputs["message"] = args ? args.message : undefined;
            inputs["monitorId"] = args ? args.monitorId : undefined;
            inputs["recurrence"] = args ? args.recurrence : undefined;
            inputs["scopes"] = args ? args.scopes : undefined;
            inputs["start"] = args ? args.start : undefined;
            inputs["startDate"] = args ? args.startDate : undefined;
        }
        super("datadog:index/datadogDowntime:DatadogDowntime", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DatadogDowntime resources.
 */
export interface DatadogDowntimeState {
    readonly active?: pulumi.Input<boolean>;
    readonly disabled?: pulumi.Input<boolean>;
    readonly end?: pulumi.Input<number>;
    readonly endDate?: pulumi.Input<string>;
    readonly message?: pulumi.Input<string>;
    readonly monitorId?: pulumi.Input<number>;
    readonly recurrence?: pulumi.Input<{ period: pulumi.Input<number>, type: pulumi.Input<string>, untilDate?: pulumi.Input<number>, untilOccurrences?: pulumi.Input<number>, weekDays?: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly scopes?: pulumi.Input<pulumi.Input<string>[]>;
    readonly start?: pulumi.Input<number>;
    readonly startDate?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DatadogDowntime resource.
 */
export interface DatadogDowntimeArgs {
    readonly active?: pulumi.Input<boolean>;
    readonly disabled?: pulumi.Input<boolean>;
    readonly end?: pulumi.Input<number>;
    readonly endDate?: pulumi.Input<string>;
    readonly message?: pulumi.Input<string>;
    readonly monitorId?: pulumi.Input<number>;
    readonly recurrence?: pulumi.Input<{ period: pulumi.Input<number>, type: pulumi.Input<string>, untilDate?: pulumi.Input<number>, untilOccurrences?: pulumi.Input<number>, weekDays?: pulumi.Input<pulumi.Input<string>[]> }>;
    readonly scopes: pulumi.Input<pulumi.Input<string>[]>;
    readonly start?: pulumi.Input<number>;
    readonly startDate?: pulumi.Input<string>;
}
