// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DatadogUser extends pulumi.CustomResource {
    /**
     * Get an existing DatadogUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatadogUserState, opts?: pulumi.CustomResourceOptions): DatadogUser {
        return new DatadogUser(name, <any>state, { ...opts, id: id });
    }

    public readonly accessRole: pulumi.Output<string | undefined>;
    public readonly disabled: pulumi.Output<boolean | undefined>;
    public readonly email: pulumi.Output<string>;
    public readonly handle: pulumi.Output<string>;
    public readonly isAdmin: pulumi.Output<boolean | undefined>;
    public readonly name: pulumi.Output<string>;
    public readonly role: pulumi.Output<string | undefined>;
    public /*out*/ readonly verified: pulumi.Output<boolean>;

    /**
     * Create a DatadogUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DatadogUserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatadogUserArgs | DatadogUserState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: DatadogUserState = argsOrState as DatadogUserState | undefined;
            inputs["accessRole"] = state ? state.accessRole : undefined;
            inputs["disabled"] = state ? state.disabled : undefined;
            inputs["email"] = state ? state.email : undefined;
            inputs["handle"] = state ? state.handle : undefined;
            inputs["isAdmin"] = state ? state.isAdmin : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["role"] = state ? state.role : undefined;
            inputs["verified"] = state ? state.verified : undefined;
        } else {
            const args = argsOrState as DatadogUserArgs | undefined;
            if (!args || args.email === undefined) {
                throw new Error("Missing required property 'email'");
            }
            if (!args || args.handle === undefined) {
                throw new Error("Missing required property 'handle'");
            }
            inputs["accessRole"] = args ? args.accessRole : undefined;
            inputs["disabled"] = args ? args.disabled : undefined;
            inputs["email"] = args ? args.email : undefined;
            inputs["handle"] = args ? args.handle : undefined;
            inputs["isAdmin"] = args ? args.isAdmin : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["role"] = args ? args.role : undefined;
            inputs["verified"] = undefined /*out*/;
        }
        super("datadog:index/datadogUser:DatadogUser", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DatadogUser resources.
 */
export interface DatadogUserState {
    readonly accessRole?: pulumi.Input<string>;
    readonly disabled?: pulumi.Input<boolean>;
    readonly email?: pulumi.Input<string>;
    readonly handle?: pulumi.Input<string>;
    readonly isAdmin?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly role?: pulumi.Input<string>;
    readonly verified?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a DatadogUser resource.
 */
export interface DatadogUserArgs {
    readonly accessRole?: pulumi.Input<string>;
    readonly disabled?: pulumi.Input<boolean>;
    readonly email: pulumi.Input<string>;
    readonly handle: pulumi.Input<string>;
    readonly isAdmin?: pulumi.Input<boolean>;
    readonly name?: pulumi.Input<string>;
    readonly role?: pulumi.Input<string>;
}
